# Use a lightweight JRE image that matches the Jenkins build environment
FROM eclipse-temurin:21-jre

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file already generated by the Jenkins 'Build' stage
# Using a wildcard to match the specific version generated by Maven
COPY target/*.jar app.jar

# Expose the application port
EXPOSE 8080

# Define the execution command
ENTRYPOINT ["java", "-jar", "app.jar"]
